### ISSUE TITLE
Makes Mod Is Compatible With BE

### ISSUE THREAD

**Issue by Tempesyad05** [Ferlern/extended-UI#7]
Hello, Ferlern. I opened this issue because i want this mod is **Compatible with BE**. please fix it **Fastly**. i proud your mod 👍🏽 

Tempesyad05

**Comment by Ferlern** [comment]
Hello. https://github.com/Ferlern/extended-UI/tree/BE-build
Main branch still for v6 & v7 alpha. You will have to manually download from here.

I want to warn you right away: I fixed only critical problems. Some features may not work / work incorrectly.
If you find a new critical bug due to new BE changes, please let me know. I don't watch them.

But please remember that the BE architecture is still subject to change, I don't want to waste too much time. I will create a full and stable version as soon as v7 is released.

**Comment by 1stvaliduser** [comment]
@Ferlern I think it has already been released)
